"""
AutoCoder Daemon Service
=========================
A persistent background service for autonomous code management.
Like OpenCode, Claude Code, or Copilot - manages projects autonomously.

Features:
- Directory watching for file changes
- Autonomous code generation without LLM dependency
- Project scaffolding and management
- Build/test execution
- Real-time code assistance
"""

import os
import sys
import json
import time
import logging
import argparse
import threading
import subprocess
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional, Callable
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


@dataclass
class ProjectConfig:
    """Configuration for a managed project."""
    name: str
    path: str
    language: str
    framework: str = ""
    test_framework: str = ""
    build_command: str = ""
    test_command: str = ""
    lint_command: str = ""
    auto_format: bool = True
    watch_patterns: list[str] = field(default_factory=lambda: ["*.py", "*.js", "*.ts"])


@dataclass
class CodeSnippet:
    """Represents a code generation template."""
    name: str
    language: str
    category: str
    template: str
    description: str


class AutoCoderDaemon:
    """Background daemon for autonomous code management."""

    def __init__(self, port: int = 8765):
        self.port = port
        self.projects: dict[str, ProjectConfig] = {}
        self.snippets = self._load_snippets()
        self.watchers: dict[str, threading.Thread] = {}
        self.is_running = False
        self._server = None

    def _load_snippets(self) -> list[CodeSnippet]:
        """Load built-in code snippets."""
        return [
            # Python snippets
            CodeSnippet("fastapi-basic", "python", "api", '''from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime

app = FastAPI(title="{name}", version="1.0.0")

class {Model}(BaseModel):
    id: Optional[int] = None
    created_at: datetime = datetime.now()

@app.get("/")
def root():
    return {{"message": "{name} API", "version": "1.0.0"}}

@app.get("/health")
def health():
    return {{"status": "healthy"}}

@app.get("/{{resource}}", response_model=List[{Model}])
def list_{resource}(skip: int = 0, limit: int = 100):
    return []

@app.post("/{{resource}}", response_model={Model})
def create_{resource}(item: {Model}):
    return item

@app.get("/{{resource}}/{{item_id}}", response_model={Model})
def get_{resource}(item_id: int):
    raise HTTPException(status_code=404, detail="Not found")

@app.put("/{{resource}}/{{item_id}}", response_model={Model})
def update_{resource}(item_id: int, item: {Model}):
    return item

@app.delete("/{{resource}}/{{item_id}}")
def delete_{resource}(item_id: int):
    return {{"deleted": True}}
''', "Basic FastAPI CRUD API"),

            CodeSnippet("flask-basic", "python", "api", '''from flask import Flask, request, jsonify
from datetime import datetime

app = Flask(__name__)

@app.route("/")
def index():
    return jsonify({{"message": "{name} API"}})

@app.route("/health")
def health():
    return jsonify({{"status": "healthy"}})

@app.route("/api/resource", methods=["GET"])
def list_resources():
    return jsonify([])

@app.route("/api/resource", methods=["POST"])
def create_resource():
    return jsonify(request.get_json()), 201

@app.route("/api/resource/<int:resource_id>", methods=["GET"])
def get_resource(resource_id):
    return jsonify({{"id": resource_id}}), 404

if __name__ == "__main__":
    app.run(debug=True, port=5000)
''', "Basic Flask API"),

            CodeSnippet("pytest-basic", "python", "test", '''import pytest
from unittest.mock import Mock, patch, MagicMock

class Test{name}:
    @pytest.fixture
    def subject(self):
        from {module} import {Class}
        return {Class}()

    def test_initialization(self, subject):
        assert subject is not None

    def test_{method}_success(self, subject):
        result = subject.{method}(test_input)
        assert result == expected_output

    def test_{method}_failure(self, subject):
        with pytest.raises(Exception):
            subject.{method}(invalid_input)

    @patch("{module}.{external}")
    def test_with_mock(self, mock_external, subject):
        mock_external.return_value = mock_value
        result = subject.{method}(input)
        mock_external.assert_called_once()
''', "Basic pytest test template"),

            CodeSnippet("class-basic", "python", "class", '''class {name}:
    """Autogenerated class for {description}"""
    
    def __init__(self{params}):
        {init_body}
    
    def __repr__(self):
        return f"{name}({repr_attrs})"
    
    def __str__(self):
        return f"{name}: {str_attrs}"
    
    @property
    def {property}(self):
        return self._{property}
    
    @{property}.setter
    def {property}(self, value):
        self._{property} = value
    
    def {method}(self{params}):
        """{method_doc}"""
        {method_body}
        return {return_value}
''', "Python class template"),

            # JavaScript snippets
            CodeSnippet("express-basic", "javascript", "api", '''const express = require("express");
const cors = require("cors");
const app = express();

app.use(cors());
app.use(express.json());

// Middleware
app.use((req, res, next) => {{
    console.log(`{{req.method}} {{req.path}}`);
    next();
}});

// Routes
app.get("/", (req, res) => {{
    res.json({{ message: "{name} API" }});
}});

app.get("/health", (req, res) => {{
    res.json({{ status: "healthy" }});
}});

app.get("/api/{resource}", (req, res) => {{
    res.json([]);
}});

app.post("/api/{resource}", (req, res) => {{
    res.json(req.body), 201;
}});

app.get("/api/{resource}/:id", (req, res) => {{
    res.json({{ id: req.params.id }}), 404;
}});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {{
    console.log(`Server running on port ${{PORT}}`);
}});
''', "Basic Express API"),

            CodeSnippet("react-component", "javascript", "frontend", '''import React, {{ useState, useEffect }} from 'react';
import PropTypes from 'prop-types';

export default function {name}({{ props }}) {{
    const [state, setState] = useState(initialValue);

    useEffect(() => {{
        // Side effect on mount
        return () => {{ 
            // Cleanup on unmount
        }};
    }}, []);

    const handleAction = (event) => {{
        setState(newValue);
    }};

    return (
        <div className="{name.toLowerCase()}">
            <h1>{name}</h1>
            <p>Current state: {{state}}</p>
            <button onClick={{handleAction}}>
                Action
            </button>
        </div>
    );
}}

{name}.propTypes = {{
    props: PropTypes.string
}};
''', "React functional component"),

            # SQL snippets
            CodeSnippet("postgres-table", "sql", "database", '''-- PostgreSQL table: {name}
CREATE TABLE {table_name} (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL
);

-- Indexes
CREATE INDEX idx_{table_name}_name ON {table_name}(name);
CREATE INDEX idx_{table_name}_email ON {table_name}(email);
CREATE INDEX idx_{table_name}_created ON {table_name}(created_at);

-- RLS (Row Level Security)
ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_can_read_own" ON {table_name}
    FOR SELECT USING (true);
''', "PostgreSQL table template"),

            # DevOps snippets
            CodeSnippet("dockerfile", "docker", "devops", '''FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

# Create non-root user
RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser

# Expose port
EXPOSE {port}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
    CMD python -c "import requests; requests.get('http://localhost:{port}/health')"

# Run application
CMD ["python", "main.py"]
''', "Dockerfile template"),

            CodeSnippet("github-action", "yaml", "devops", '''name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run tests
        run: |
          pytest --cov=. --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ruff
        uses: chartboost/ruff-action@v1
''', "GitHub Actions CI"),
        ]

    def add_project(self, config: ProjectConfig):
        """Add a project to manage."""
        self.projects[config.path] = config
        logger.info(f"Added project: {config.name} at {config.path}")
        
        # Start watching if auto-watch enabled
        self._start_watcher(config)

    def remove_project(self, path: str):
        """Remove a project."""
        if path in self.projects:
            config = self.projects.pop(path)
            if path in self.watchers:
                self.watchers[path].join(timeout=2)
                del self.watchers[path]
            logger.info(f"Removed project: {config.name}")

    def generate_code(self, request: str, context: dict = None) -> str:
        """Generate code autonomously based on templates."""
        request_lower = request.lower()
        context = context or {}
        
        # Try to match a snippet
        for snippet in self.snippets:
            if self._matches_request(snippet, request_lower):
                return self._render_snippet(snippet, request, context)
        
        # Fall back to template matching
        if "fastapi" in request_lower or ("api" in request_lower and "python" in request_lower):
            return self._render_snippet_by_name("fastapi-basic", request, context)
        if "flask" in request_lower:
            return self._render_snippet_by_name("flask-basic", request, context)
        if "react" in request_lower or "component" in request_lower:
            return self._render_snippet_by_name("react-component", request, context)
        if "express" in request_lower or "node" in request_lower:
            return self._render_snippet_by_name("express-basic", request, context)
        if "test" in request_lower:
            return self._render_snippet_by_name("pytest-basic", request, context)
        if "class" in request_lower:
            return self._render_snippet_by_name("class-basic", request, context)
        if "docker" in request_lower:
            return self._render_snippet_by_name("dockerfile", request, context)
        
        # Default template code
        return self._generate_default(request)

    def _matches_request(self, snippet: CodeSnippet, request: str) -> bool:
        """Check if snippet matches request."""
        keywords = [
            snippet.name.lower().replace("-", " "),
            snippet.category,
            snippet.language
        ]
        return any(kw in request for kw in keywords if kw)

    def _render_snippet(self, snippet: CodeSnippet, request: str, context: dict) -> str:
        """Render a matched snippet with context."""
        name = context.get("name", "Resource")
        module = context.get("module", "app")
        table_name = context.get("table", name.lower() + "s")
        
        template = snippet.template
        template = template.replace("{name}", name.title())
        template = template.replace("{Class}", name.title())
        template = template.replace("{table_name}", table_name)
        template = template.replace("{module}", module)
        template = template.replace("{resource}", name.lower())
        template = template.replace("{property}", "value")
        template = template.replace("{method}", "do_something")
        template = template.replace("{method_doc}", "Do something")
        template = template.replace("{params}", "")
        template = template.replace("{init_body}", "pass")
        template = template.replace("{repr_attrs}", "")
        template = template.replace("{str_attrs}", "")
        template = template.replace("{method_body}", "pass")
        template = template.replace("{return_value}", "None")
        template = template.replace("{props}", "")
        template = template.replace("{port}", "8000")
        
        return template

    def _render_snippet_by_name(self, name: str, request: str, context: dict) -> str:
        """Render snippet by name."""
        for snippet in self.snippets:
            if snippet.name == name:
                return self._render_snippet(snippet, request, context)
        return self._generate_default(request)

    def _generate_default(self, request: str) -> str:
        """Generate default code based on request type."""
        request_lower = request.lower()
        
        if "python" in request_lower:
            return '''# AutoCoder Generated Python Code
# Edit this file and save to create your implementation

def main():
    print("AutoCoder: Implement your logic here")

if __name__ == "__main__":
    main()
'''
        if "javascript" in request_lower or "js" in request_lower:
            return '''// AutoCoder Generated JavaScript Code
// Edit this file and save to create your implementation

function main() {
    console.log("AutoCoder: Implement your logic here");
}

main();
'''
        if "sql" in request_lower:
            return '''-- AutoCoder Generated SQL
-- Edit this table definition

CREATE TABLE example (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
'''
        return f'''// AutoCoder: Code generation for: {request}
// This is a placeholder - configure your project for full generation

{request}
'''

    def _start_watcher(self, config: ProjectConfig):
        """Start file watcher for a project."""
        def watch():
            import time
            last_mtime = {}
            while config.path in self.projects:
                try:
                    for pattern in config.watch_patterns:
                        for file in Path(config.path).rglob(pattern):
                            if file.is_file():
                                mtime = file.stat().st_mtime
                                if file not in last_mtime or mtime > last_mtime[file]:
                                    last_mtime[file] = mtime
                                    logger.info(f"File changed: {file}")
                                    # Could trigger rebuild, lint, etc.
                except Exception as e:
                    logger.error(f"Watcher error: {e}")
                time.sleep(2)
        
        thread = threading.Thread(target=watch, daemon=True)
        thread.start()
        self.watchers[config.path] = thread
        logger.info(f"Started watcher for {config.name}")

    def create_project(self, name: str, path: str, language: str, framework: str = "") -> bool:
        """Scaffold a new project."""
        project_path = Path(path) / name
        project_path.mkdir(parents=True, exist_ok=True)
        
        config = ProjectConfig(
            name=name,
            path=str(project_path),
            language=language,
            framework=framework,
            test_framework=self._detect_test_framework(language, framework),
            build_command=self._detect_build_command(language, framework),
            test_command=self._detect_test_command(language, framework),
        )
        
        # Create project structure
        self._scaffold_project(config)
        
        self.add_project(config)
        return True

    def _detect_test_framework(self, language: str, framework: str) -> str:
        """Detect appropriate test framework."""
        mapping = {
            ("python", "fastapi"): "pytest",
            ("python", "flask"): "pytest",
            ("python", "django"): "pytest",
            ("javascript", "react"): "jest",
            ("javascript", "vue"): "vitest",
            ("javascript", "express"): "jest",
            ("typescript", "react"): "jest",
            ("typescript", "angular"): "jest",
        }
        return mapping.get((language.lower(), framework.lower()), "pytest")

    def _detect_build_command(self, language: str, framework: str) -> str:
        """Detect build command."""
        mapping = {
            ("python", "fastapi"): "uvicorn main:app --reload",
            ("python", "flask"): "flask run",
            ("python", "django"): "python manage.py runserver",
            ("javascript", "react"): "npm start",
            ("javascript", "vue"): "npm run dev",
            ("javascript", "express"): "node index.js",
            ("typescript", "react"): "npm start",
        }
        return mapping.get((language.lower(), framework.lower()), "python main.py")

    def _detect_test_command(self, language: str, framework: str) -> str:
        """Detect test command."""
        if language.lower() == "python":
            return "pytest"
        if language.lower() in ("javascript", "typescript"):
            return "npm test"
        return "echo 'No tests configured'"

    def _scaffold_project(self, config: ProjectConfig):
        """Create project files."""
        project_path = Path(config.path)
        
        if config.language.lower() == "python":
            (project_path / "main.py").write_text(f'''""" {config.name} - AutoCoder generated """
from fastapi import FastAPI

app = FastAPI(title="{config.name}")

@app.get("/")
def root():
    return {{"message": "{config.name}"}}

@app.get("/health")
def health():
    return {{"status": "healthy"}}
''')
            (project_path / "requirements.txt").write_text("fastapi\nuvicorn\npytest\n")
            (project_path / ".gitignore").write_text("__pycache__/\n*.pyc\nvenv/\n.env\n")
        
        elif config.language.lower() in ("javascript", "typescript"):
            (project_path / "package.json").write_text(json.dumps({
                "name": config.name,
                "version": "1.0.0",
                "main": "index.js",
                "scripts": {
                    "start": "node index.js",
                    "test": "jest"
                }
            }, indent=2))
            (project_path / "index.js").write_text(f'''// {config.name}
console.log("{config.name} running...");
''')

    def run_build(self, project_path: str) -> dict:
        """Run build for a project."""
        config = self.projects.get(project_path)
        if not config:
            return {"success": False, "error": "Project not found"}
        
        try:
            result = subprocess.run(
                config.build_command,
                shell=True,
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=120
            )
            return {
                "success": result.returncode == 0,
                "output": result.stdout,
                "errors": result.stderr
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    def run_tests(self, project_path: str) -> dict:
        """Run tests for a project."""
        config = self.projects.get(project_path)
        if not config:
            return {"success": False, "error": "Project not found"}
        
        try:
            result = subprocess.run(
                config.test_command,
                shell=True,
                cwd=project_path,
                capture_output=True,
                text=True,
                timeout=120
            )
            return {
                "success": result.returncode == 0,
                "output": result.stdout,
                "errors": result.stderr
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    def start_server(self, port: int = None):
        """Start the daemon HTTP server."""
        from http.server import HTTPServer, BaseHTTPRequestHandler
        import threading
        
        port = port or self.port
        
        class Handler(BaseHTTPRequestHandler):
            def do_GET(self):
                if self.path == "/health":
                    self.send_response(200)
                    self.send_header("Content-Type", "application/json")
                    self.end_headers()
                    self.wfile.write(json.dumps({
                        "status": "running",
                        "projects": len(daemon.projects),
                        "snippets": len(daemon.snippets)
                    }).encode())
                elif self.path == "/projects":
                    self.send_response(200)
                    self.send_header("Content-Type", "application/json")
                    self.end_headers()
                    data = {k: {"name": v.name, "language": v.language, "framework": v.framework} 
                            for k, v in daemon.projects.items()}
                    self.wfile.write(json.dumps(data).encode())
                else:
                    self.send_response(404)
                    self.end_headers()
            
            def do_POST(self):
                if self.path == "/generate":
                    length = int(self.headers.get("Content-Length", 0))
                    body = self.rfile.read(length)
                    data = json.loads(body)
                    
                    result = daemon.generate_code(data.get("prompt", ""), data.get("context", {}))
                    
                    self.send_response(200)
                    self.send_header("Content-Type", "application/json")
                    self.end_headers()
                    self.wfile.write(json.dumps({"code": result}).encode())
                
                elif self.path == "/create-project":
                    length = int(self.headers.get("Content-Length", 0))
                    body = self.rfile.read(length)
                    data = json.loads(body)
                    
                    success = daemon.create_project(
                        data.get("name", "new-project"),
                        data.get("path", "."),
                        data.get("language", "python"),
                        data.get("framework", "")
                    )
                    
                    self.send_response(200 if success else 400)
                    self.send_header("Content-Type", "application/json")
                    self.end_headers()
                    self.wfile.write(json.dumps({"success": success}).encode())
                
                elif self.path == "/build":
                    length = int(self.headers.get("Content-Length", 0))
                    body = self.rfile.read(length)
                    data = json.loads(body)
                    
                    result = daemon.run_build(data.get("path", ""))
                    
                    self.send_response(200)
                    self.send_header("Content-Type", "application/json")
                    self.end_headers()
                    self.wfile.write(json.dumps(result).encode())
                
                else:
                    self.send_response(404)
                    self.end_headers()
            
            def log_message(self, format, *args):
                pass  # Suppress logging
        
        server = HTTPServer(("127.0.0.1", port), Handler)
        self.is_running = True
        
        logger.info(f"AutoCoder daemon running on port {port}")
        logger.info(f"  /health - Health check")
        logger.info(f"  /projects - List projects")
        logger.info(f"  /generate - Generate code")
        logger.info(f"  /create-project - Create new project")
        logger.info(f"  /build - Build project")
        
        server.serve_forever()


# Global daemon instance
daemon = None

def main():
    global daemon
    
    parser = argparse.ArgumentParser(description="AutoCoder Daemon")
    parser.add_argument("--port", "-p", type=int, default=8765, help="Port to run on")
    parser.add_argument("--create-project", "-c", help="Create a new project")
    parser.add_argument("--generate", "-g", help="Generate code")
    args = parser.parse_args()
    
    daemon = AutoCoderDaemon(port=args.port)
    
    if args.create_project:
        name, path, lang = args.create_project.split(":")
        daemon.create_project(name, path, lang)
        print(f"Created project: {name}")
    
    if args.generate:
        result = daemon.generate_code(args.generate)
        print(result)
        return
    
    # Start as daemon server
    daemon.start_server()


if __name__ == "__main__":
    main()
